spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true
    properties:
      hibernate.format_sql: true
      hibernate.default_batch_fetch_size: 100

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa


logging:
  level:
    study.toy: debug
    org.springframework.web.servlet: debug
    # jpa show query data binding
    org.hibernate.type.descriptor.sql.BasicBinder: trace

